### ISSUE TITLE
SVG import from node_modules

### ISSUE THREAD

**Issue by malua** [nathantreid/meteor-static-assets#7]
Hey nathan,
first of all thanks for your work!

I am trying to get ionic (react) going with meteor. ionic only uses ES module exports so i am following [this guide](https://forums.meteor.com/t/litelement-import-litelement-html/45042/8) to recompile @ionic/core and @ionic/react. this is working so far. but ionic depends on ionicons (an icon package) which is a seperate npm module. this package imports svg files like this:

`import iosAddCircleOutline from './ios-add-circle-outline.svg';`

as far as i understood your plugin can handle such import statements in npm modules, but i only get an compiler error as meteor doesn't understand the import statment.

if add a symlink to ionicons as well, it gets recompiled to

```
let iosAddCircleOutline;
module.link("./ios-add-circle-outline.svg", {
  default(v) {
    iosAddCircleOutline = v;
  }
}, 0);
```

no compiler error anymore, but rather `Cannot find module './ios-add-circle-outline.svg'`.

so maybe you have any idea how this could be fixed? thanks very much in advance, also i understand this is not an "issue" with your plugin, but i would still very much appreciate your help if you got the time.

**Comment by akanix42** [comment]
I'll take a look. Would you be able to provide a reproduction repo?

**Comment by malua** [comment]
of course. i will try to do it this evening

**Comment by malua** [comment]
I created a basic repo to showcase the error. it has only the necessary packages.
I already created symlinks to let meteor recompile the packages. if you clone it and run it, you will get an error that an svg file cannot be found. if you remove the ionicons symlink in "imports/links/" you will get a compile error, as meteor does not know the import statment. 

[https://github.com/malua/meteor-react-ionic](https://github.com/malua/meteor-react-ionic)

if you have any questions, i will try to answer as fast as possible. thanks so much!

**Comment by akanix42** [comment]
I took a look, but all I can say is that something with the symlink is breaking it. Without the symlink, you can import the file directly. For example here is an adjusted `main.jsx`:
```jsx
import svg from 'ionicons/dist/ionicons/svg/ios-add-circle-outline.svg';
console.log('svg', svg)

// import React from "react";
// import { Meteor } from "meteor/meteor";
// import { render } from "react-dom";
// import App from "/imports/ui/App";
// import {
//   IonApp,
//   IonContent,
//   IonCard,
//   IonCardHeader,
//   IonCardTitle,
//   IonCardSubtitle
// } from "@ionic/react";

// Meteor.startup(() => {
//   render(<App />, document.getElementById("react-target"));
// });
```
This outputs `svg http://localhost:3000/static/node_modules/ionicons/dist/ionicons/svg/ios-add-circle-outline.svg` and the svg is accessible at the supplied link.

However, once I add the `ionicons` symlink I instead get the `Cannot find module` error like you are seeing:
```
modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:232 Uncaught Error: Cannot find module 'ionicons/dist/ionicons/svg/ios-add-circle-outline.svg'
    at makeMissingError (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:232)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:251)
    at Module.moduleLink [as link] (modules.js?hash=94db6ca05773dc674277bd4e840289c8d5b003f2:291)
    at main.jsx (app.js?hash=28b3fdb5391b5ac3decc5cc64c5bf582e28da28c:10)
    at fileEvaluate (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:346)
    at Module.require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:248)
    at require (modules-runtime.js?hash=d3c3e5d67c95f97a60888bda7373292efad3be5e:268)
    at app.js?hash=28b3fdb5391b5ac3decc5cc64c5bf582e28da28c:44
```

The only thing I could think of with my plugin was perhaps some sort of issue since Meteor 1.8 made `CachingCompiler.processFilesForTarget` async, but I updated the code for that and it didn't make a difference.
I recommend opening an issue with [meteor/meteor](https://github.com/meteor/meteor/issues) since at this point it seems to me like it's caused by the symlink handling.

**Comment by malua** [comment]
Thanks for your help! As you can see i have opened an issue on meteor/meteor.
I will close this issue for now, and if someone finds an solution, I will add it here for completeness
